### ISSUE TITLE
Users can see their car 

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Add an image of a car to the HTML
- [x] Add css styling 
- [x] Fix any errors
