### ISSUE TITLE
Users can turn their car

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create data model that includes direction the car is facing (north, south, east, or west) 
- [x] Listen for 'keydown' events on the document to turn the car the direction of the key pressed.
  - [x] If right key is pressed, car faces east.
  - [x] If left key is pressed, car faces west.
  - [x] if up key is pressed, car faces north.
  - [x] if down key is pressed, car faces south.
