### ISSUE TITLE
Users can start their car

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add location that stores the car’s x and y coordinates on the page to the data model.
- [x] Update keydown function so that: 
  - [x] If space is pressed, the car moves a few pixels. 
  - [x] Add a timer that represents the car moving every 16 milliseconds when space is pressed.
