### ISSUE TITLE
Users can stop their car 

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean to data model to indicate whether or not the car is started
- [x] Update keydown function:
  - [x] If car has not started, space should move the car
  - [x] If car has started, space should stop the car
