### ISSUE TITLE
Users can steer their car

### ISSUE THREAD

**Issue by ashleylho** [ashleylho/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Update keydown function to show:
  - [x] If the car is facing north, car moves up if it has started
  - [x] If the car is facing south, car moves down if it has started
  - [x] If the car is facing east, car moves right if it has started
  - [x] If the car is facing west, car moves left if it has started
